apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo-deployment
  namespace: demo-k8s
  labels:
    app: web-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
        - name: web-demo
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-demo-secret
                  key: APP_SECRET
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: web-content
          configMap:
            name: web-demo-config
