apiVersion: v1
kind: ConfigMap
metadata:
  name: web-demo-config
  namespace: demo-k8s
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>Web Demo on Kubernetes</title>
    </head>
    <body>
      <h1>Kubernetes Deployment + Service + Ingress</h1>
      <p>ConfigMap: web-demo-config</p>
    </body>
    </html>

---
apiVersion: v1
kind: Secret
metadata:
  name: web-demo-secret
  namespace: demo-k8s
type: Opaque
stringData:
  APP_SECRET: "CHANGE_ME_IN_REAL_ENV"
