apiVersion: v1
kind: Service
metadata:
  name: web-demo-service
  namespace: demo-k8s
spec:
  type: NodePort      # เล่นบน minikube ง่าย ๆ
  selector:
    app: web-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
